server:
  address: ":50051"

keystore:
  path: "keystore"
  # 128 subnet entries
  subnets:
    - id: "subnet0"
    - id: "subnet1"
    - id: "subnet2"
    - id: "subnet3"
    - id: "subnet4"
    - id: "subnet5"
    - id: "subnet6"
    - id: "subnet7"
    - id: "subnet8"
    - id: "subnet9"
    - id: "subnet10"
    - id: "subnet11"
    - id: "subnet12"
    - id: "subnet13"
    - id: "subnet14"
    - id: "subnet15"
    - id: "subnet16"
    - id: "subnet17"
    - id: "subnet18"
    - id: "subnet19"
    - id: "subnet20"
    - id: "subnet21"
    - id: "subnet22"
    - id: "subnet23"
    - id: "subnet24"
    - id: "subnet25"
    - id: "subnet26"
    - id: "subnet27"
    - id: "subnet28"
    - id: "subnet29"
    - id: "subnet30"
    - id: "subnet31"
    - id: "subnet32"
    - id: "subnet33"
    - id: "subnet34"
    - id: "subnet35"
    - id: "subnet36"
    - id: "subnet37"
    - id: "subnet38"
    - id: "subnet39"
    - id: "subnet40"
    - id: "subnet41"
    - id: "subnet42"
    - id: "subnet43"
    - id: "subnet44"
    - id: "subnet45"
    - id: "subnet46"
    - id: "subnet47"
    - id: "subnet48"
    - id: "subnet49"
    - id: "subnet50"
    - id: "subnet51"
    - id: "subnet52"
    - id: "subnet53"
    - id: "subnet54"
    - id: "subnet55"
    - id: "subnet56"
    - id: "subnet57"
    - id: "subnet58"
    - id: "subnet59"
    - id: "subnet60"
    - id: "subnet61"
    - id: "subnet62"
    - id: "subnet63"
    - id: "subnet64"
    - id: "subnet65"
    - id: "subnet66"
    - id: "subnet67"
    - id: "subnet68"
    - id: "subnet69"
    - id: "subnet70"
    - id: "subnet71"
    - id: "subnet72"
    - id: "subnet73"
    - id: "subnet74"
    - id: "subnet75"
    - id: "subnet76"
    - id: "subnet77"
    - id: "subnet78"
    - id: "subnet79"
    - id: "subnet80"
    - id: "subnet81"
    - id: "subnet82"
    - id: "subnet83"
    - id: "subnet84"
    - id: "subnet85"
    - id: "subnet86"
    - id: "subnet87"
    - id: "subnet88"
    - id: "subnet89"
    - id: "subnet90"
    - id: "subnet91"
    - id: "subnet92"
    - id: "subnet93"
    - id: "subnet94"
    - id: "subnet95"
    - id: "subnet96"
    - id: "subnet97"
    - id: "subnet98"
    - id: "subnet99"
    - id: "subnet100"
    - id: "subnet101"
    - id: "subnet102"
    - id: "subnet103"
    - id: "subnet104"
    - id: "subnet105"
    - id: "subnet106"
    - id: "subnet107"
    - id: "subnet108"
    - id: "subnet109"
    - id: "subnet110"
    - id: "subnet111"
    - id: "subnet112"
    - id: "subnet113"
    - id: "subnet114"
    - id: "subnet115"
    - id: "subnet116"
    - id: "subnet117"
    - id: "subnet118"
    - id: "subnet119"
    - id: "subnet120"
    - id: "subnet121"
    - id: "subnet122"
    - id: "subnet123"
    - id: "subnet124"
    - id: "subnet125"
    - id: "subnet126"
    - id: "subnet127"

tls:
  enabled: false
  cert_path: "certs/server.crt"
  key_path: "certs/server.key"
  client_auth: false
  ca_path: "certs/ca.crt"

metrics:
  enabled: true
  address: ":9090"

log:
  level: "info"
  format: "json"
